#!/bin/bash
# --------------------------------------------------------------------
# Boilerplate example
# -------------------
# For scripts that are to be made public, or not
#
# Author: Michael Zeltner <m@niij.org>
#         4096R/6CAC71020AF5D60D
# License: Public Domain
# Date: 15 Oct 2013
# Version: 0.1
# --------------------------------------------------------------------
