#!/bin/bash
# --------------------------------------------------------------------
# Boilerplate example
# -------------------
# For scripts that are to be made public, or not
#
# Author: Michael Zeltner <m@niij.org>
#         rsa8192/5DE83E90EFFCDDF9
# License: Public Domain
# Date: 15 Oct 2013
# Version: 0.1
# --------------------------------------------------------------------
