#!/bin/bash
# --------------------------------------------------------------------
# manualocsp
# ----------
#
# Author: Michael Zeltner <m@niij.org>
#         rsa8192/5DE83E90EFFCDDF9
# License: Public Domain
# Date: 09 Mar 2016
# Version: 0.2
# --------------------------------------------------------------------

BN=$(basename $0)

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "" ]; then
    echo $BN -- cron helper to download the most recent ocsp response
    echo
    echo Help:
    echo "$ $BN ISSUER CAFILE URL CERTIFICATE FILE [POSTDOWNLOADCOMMAND]"
    echo
    echo Examples:
    echo "$ $BN myca.pem mycabundle.pem http://ocsp.myca.example.org/ mycert.crt mycert-ocspresponse.der 'systemctl restart nginx.service'"
    exit 0
fi

ISSUER=$1
CAFILE=$2
URL="$3"
HOST=$(sed -e 's,.*//\([-.a-zA-Z0-9]*\)/.*,\1,g'<<<"$3")
CERTIFICATE=$4
OUT=$5
POST=$6
SERIAL="0x$(openssl x509 -in $4 -serial -noout | egrep -o "[A-Z0-9]*")"

COMMAND="openssl ocsp -issuer $ISSUER -CAfile $CAFILE"
REQ="-nonce -url $URL -header Host $HOST -serial $SERIAL"

RESPIN="$($COMMAND -text -respin $OUT 2> /dev/null)"
RESPINSERIAL=$(grep Serial <<< "$RESPIN" | egrep -o "[A-F0-9]*")

if [ -f $OUT ]; then
    UPDATE=$(($(date --date="$(grep -oP "Next Update:.*" <<< "$RESPIN" | sed -e 's,.*: ,,')" +%s)-$((60*60*5))))
else
    UPDATE=1
fi

if [ "0x$RESPINSERIAL" != "$SERIAL" ]; then
    UPDATE=1
fi

if [ $UPDATE -lt $(date +%s) ]; then
    $COMMAND $REQ -respout $OUT -out /dev/null 2> /dev/null
    if [ "$POST" != "" ]; then
        exec $POST
    fi
fi
