#!/bin/bash
# --------------------------------------------------------------------
# manualocsp
# ----------
#
# Author: Michael Zeltner <m@niij.org>
#         rsa8192/5DE83E90EFFCDDF9
# License: Public Domain
# Date: 15 Nov 2015
# Version: 0.1
# --------------------------------------------------------------------

BN=$(basename $0)

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "" ]; then
    echo $BN -- cron helper to download the most recent ocsp response
    echo
    echo Help:
    echo "$ $BN ISSUER CAFILE URL SERIAL FILE [POSTDOWNLOADCOMMAND]"
    echo
    echo Examples:
    echo "$ $BN myca.pem mycabundle.pem http://ocsp.myca.example.org/ 0x42424242424242 mycert-ocspresponse.der 'systemctl restart nginx.service'"
    exit 0
fi

ISSUER=$1
CAFILE=$2
URL="$3"
HOST=$(sed -e 's,.*//\([-.a-zA-Z0-9]*\)/.*,\1,g'<<<"$3")
SERIAL=$4
OUT=$5
POST=$6

COMMAND="openssl ocsp -issuer $ISSUER -CAfile $CAFILE"
REQ="-nonce -url $URL -header Host $HOST -serial $SERIAL"

if [ -f $OUT ]; then
    UPDATE=$(($(date --date="$($COMMAND -text -respin $OUT 2> /dev/null | grep -oP "Next Update:.*" | sed -e 's,.*: ,,')" +%s)-$((60*60*5))))
else
    UPDATE=1
fi

if [ $UPDATE -lt $(date +%s) ]; then
    $COMMAND $REQ -respout $OUT -out /dev/null 2> /dev/null
    if [ "$POST" != "" ]; then
        exec $POST
    fi
fi
