#!/bin/bash
# --------------------------------------------------------------------
# uidshift
# --------
# Little helper script to move privileged lxc containers to
# unprivileged ones
#
# Author: Michael Zeltner <m@niij.org>
#         rsa8192/5DE83E90EFFCDDF9
# License: Public Domain
# Date: 08 Nov 2016
# Version: 0.2
# --------------------------------------------------------------------
BN=$(basename $0)

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "" ]; then
    echo $BN -- helper script to shift a folders user and group ids by N
    echo
    echo Help:
    echo "$ $BN FOLDER UID-OFFSET"
    echo
    echo Examples:
    echo "$ $BN /var/lib/lxc/container/rootfs 100000"
    exit 0
fi

FOLDER=$1
OFFSET=$2
for n in `find . -printf '%G\n%U\n'|sort -u`; do
    if [ $n -lt $(($OFFSET-1)) ]; then
        echo Changing owner for $n
        find $FOLDER -type f -uid $n -exec chown $(($OFFSET+n)) \{\} \;
        find $FOLDER -type d -uid $n -exec chown $(($OFFSET+n)) \{\} \;
        echo Changing group for $n
        find $FOLDER -type f -gid $n -exec chgrp $(($OFFSET+n)) \{\} \;
        find $FOLDER -type d -gid $n -exec chgrp $(($OFFSET+n)) \{\} \;
    fi
done
